name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        uses: jdx/mise-action@v3

      - name: Install app
        run: uv sync

      - name: Run checks
        run: just check
